apiVersion: apps/v1
kind: Deployment
metadata:
  name: uimanagement-deployment
  labels:
    app.kubernetes.io/name: uimanagement
    app.kubernetes.io/type: frontend
spec:
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app.kubernetes.io/name: uimanagement
        app.kubernetes.io/type: frontend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10001
        runAsGroup: 3000
        fsGroup: 10001
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - uimanagement
              - key: app.kubernetes.io/type
                operator: In
                values:
                - frontend
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: uimanagement-container
        image: #{acrurl}#/uiservice
        #image: acrakspzfu3h3wyefhu.azurecr.io/uiservice
        imagePullPolicy: "Always"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
             - all
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        ports:
          - containerPort: 8080
      volumes:
      - name: tmp
        emptyDir: {} 
      nodeSelector:
        agentpool: npuser01         
  selector:
    matchLabels:
        app.kubernetes.io/name: uimanagement
        app.kubernetes.io/type: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: uimanagement-service
  labels:
    svc.kubernetes.io/name: uimanagement
    svc.kubernetes.io/type: frontend
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: uimanagement
    app.kubernetes.io/type: frontend
  
---
kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: uimanagement-hpa
  labels:
    hpa.kubernetes.io/name: uimanagement
    hpa.kubernetes.io/type: frontend 
spec: 
  maxReplicas: 5 
  minReplicas: 2
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: uimanagement-deployment 
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 70