
# ============================== Filebeat inputs ===============================

filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /tmp/log/Error/*
    - /tmp/log/Info/*
  fields:
    ENV: DEV01
    ServiceName: ${serviceName}
  fields_under_root: true
  ignore_older: 72h  

# ------------------------------ Logstash Output -------------------------------
output.logstash:
   hosts: ["dafct-lan1-d-euwe-cdp-elk-ls-vm2.daf.internal:5044"]
   loadbalance: true

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
   ssl.certificate_authorities: ["/certs/dafct-lan1-d-euwe-cdp-elk-ls-vm2.crt"]
   ssl.verification_mode: none
   
# ================================= Processors =================================
processors:
  - drop_fields:
      fields: ["agent", "log", "input", "ecs" ]
