apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertservice-grpc
spec:
  selector:
    matchLabels:
      run: alertservice-grpc
  replicas: 2
  template:
    metadata:
      labels:
        run: alertservice-grpc
    spec:
      containers:
      - name: alertservice-grpc
        image: dafdev017756.azurecr.io/alertservice-grpc
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: alertservice
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: alertservice-grpc