# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
- name: ENV
  displayName: ENV
  type: string
  default: DEV0
  values:
  - All
  - DEV0
  - DEV01
  - DEV02
  - TEST01
  - TEST02
  - ACC03

pool: $(PRIVATEAGENT)

variables:
- ${{ if eq(parameters.ENV, 'DEV0') }}:
  - group: DEV0-Build-Variables
- ${{ if eq(parameters.ENV, 'DEV01') }}:
  - group: DEV01-Build-Variables
- ${{ if eq(parameters.ENV, 'DEV02') }}:
  - group: DEV02-Build-Variables
- ${{ if eq(parameters.ENV, 'TEST01') }}:
  - group: TEST01-Build-Variables
- ${{ if eq(parameters.ENV, 'All') }}:
  - group: DEV02-Build-Variables
- ${{ if eq(parameters.ENV, 'TEST02') }}:
  - group: TEST02-Build-Variables
- ${{ if eq(parameters.ENV, 'ACC03') }}:
  - group: ACC03-Build-Variables

steps:
- task: replacetokens@3
  inputs:
    targetFiles: 'dotnet/commonservices/net.atos.daf.ct2.auditservicerest/appsettings.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true
  condition: in('${{ parameters.ENV }}', 'DEV0', 'DEV01', 'DEV02', 'TEST01')

- task: CmdLine@2
  inputs:
    script: |
      cat dotnet/commonservices/net.atos.daf.ct2.auditservicerest/appsettings.json
  condition: in('${{ parameters.ENV }}', 'DEV0', 'DEV01', 'DEV02', 'TEST01')

- task: replacetokens@3
  inputs:
    targetFiles: 'dotnet/commonservices/net.atos.daf.ct2.auditservicerest/log4net.config'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true

- task: CmdLine@2
  inputs:
    script: |
      cat dotnet/commonservices/net.atos.daf.ct2.auditservicerest/log4net.config

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription:  $(Subscription)
    azureContainerRegistry: $(ContainerRegistry)
    dockerFile: dotnet/AuditServiceRest_Dockerfile
    imageName: auditservice
  condition: in('${{ parameters.ENV }}', 'DEV0', 'DEV01', 'DEV02', 'TEST01','TEST02','ACC03')

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: $(Subscription)
    azureContainerRegistry: $(ContainerRegistry)
    action: 'Push an image'
    imageName: auditservice
  condition: in('${{ parameters.ENV }}', 'DEV0', 'DEV01', 'DEV02', 'TEST01','TEST02','ACC03')

- task: CmdLine@2
  inputs:
    script: |
      echo $(ContainerRegistry)
  condition: eq('${{ parameters.ENV }}', 'All')
  
      
     
