apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditservice
spec:
  selector:
    matchLabels:
      run: auditservice
  replicas: 1
  template:
    metadata:
      labels:
        run: auditservice
    spec:
      containers:
      - name: auditservice
        image: dafdev017756.azurecr.io/auditservice
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: auditservice
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: auditservice
