apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditservice-grpc-deployment
  labels:
    app.kubernetes.io/name: auditservice-grpc
    app.kubernetes.io/type: businessservice
spec:
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app.kubernetes.io/name: auditservice-grpc
        app.kubernetes.io/type: businessservice
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - auditservice-grpc
              - key: app.kubernetes.io/type
                operator: In
                values:
                - businessservice
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: auditservice-grpc-container
        image: #{acrurl}#/auditservice-grpc
        imagePullPolicy: "Always"
        volumeMounts:
        - name: log
          mountPath: /app/log
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
             - all
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:8080"
        - name: COMPlus_EnableDiagnostics
          value: "0"
        ports:
          - containerPort: 8080
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 10001:10001 /app/log"]    
      volumes:
      - name: log
        emptyDir: {}
      nodeSelector:
        agentpool: npuser01         
  selector:
    matchLabels:
        app.kubernetes.io/name: auditservice-grpc
        app.kubernetes.io/type: businessservice
---
apiVersion: v1
kind: Service
metadata:
  name: auditservice
  labels:
    svc.kubernetes.io/name: auditservice-grpc
    svc.kubernetes.io/type: businessservice
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: auditservice-grpc
    app.kubernetes.io/type: businessservice

---
kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: auditservice-grpc-hpa
  labels:
    hpa.kubernetes.io/name: auditservice-grpc
    hpa.kubernetes.io/type: businessservice 
spec: 
  maxReplicas: 5 
  minReplicas: 2
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: auditservice-grpc-deployment 
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 70