# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

jobs:
  - job:
    pool: $(PRIVATEAGENT)
    variables:
    - group: DEV01-Build-Variables
    - name: a
      value: 'DAF CT AZURE DTA LANDING ZONE DEV1'
    - name: b
      value: '{"loginServer":"acrakspzfu3h3wyefhu.azurecr.io", "id" : "/subscriptions/6bd8b39f-86c3-4026-985a-34db67361301/resourceGroups/daf-lan1-d-euwe-rsg-aks/providers/Microsoft.ContainerRegistry/registries/acrakspzfu3h3wyefhu"}'
    steps:
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            cat dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json
      
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            echo $(Subscription)
            echo $(ContainerRegistry)
      
      - task: Docker@0
        displayName: 'Build an image'
        inputs:
          azureSubscription: ${{ variables.a }}
          azureContainerRegistry: ${{ variables.b }}
          dockerFile: dotnet/AccountService_Dockerfile
          imageName: accountservice-grpc-automatic

      - task: Docker@0
        displayName: 'Push an image'
        inputs:
          azureSubscription: ${{ variables.a }}
          azureContainerRegistry: ${{ variables.b }}
          action: 'Push an image'
          imageName: accountservice-grpc-automatic
    
  - job:
    pool: $(PRIVATEAGENT)
    variables:
    - group: DEV0-Build-Variables
    - name: a
      value: 'ats-sub1-d-app-automation'
    - name: b
      value: '{"loginServer":"dafdev017756.azurecr.io", "id" : "/subscriptions/f0b7c74e-ef18-46e8-ae31-7abbd0e5fd8f/resourceGroups/DAFCT_DEV0_DTA_K8S/providers/Microsoft.ContainerRegistry/registries/dafdev017756"}'
    steps:
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            cat dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json
      
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            echo $(Subscription)
            echo $(ContainerRegistry)
      
      - task: Docker@0
        displayName: 'Build an image'
        inputs:
          azureSubscription: ${{ variables.a }}
          azureContainerRegistry: ${{ variables.b }}
          dockerFile: dotnet/AccountService_Dockerfile
          imageName: accountservice-grpc-automatic

      - task: Docker@0
        displayName: 'Push an image'
        inputs:
          azureSubscription: ${{ variables.a }}
          azureContainerRegistry: ${{ variables.b }}
          action: 'Push an image'
          imageName: accountservice-grpc-automatic