# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

jobs:
  - job:
    variables:
      - group: DEV01-Build-Variables
      - name: a
        value: '{"loginServer":"acrakspzfu3h3wyefhu.azurecr.io", "id" : "/subscriptions/6bd8b39f-86c3-4026-985a-34db67361301/resourceGroups/daf-lan1-d-euwe-rsg-aks/providers/Microsoft.ContainerRegistry/registries/acrakspzfu3h3wyefhu"}'
    pool: $(PRIVATEAGENT)
    steps:
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            cat dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json
      
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            echo $(a)
      
      - task: Docker@2
        inputs:
          containerRegistry: 'acrRegistryServiceConnection1'
          repository: '{"loginServer":"acrakspzfu3h3wyefhu.azurecr.io", "id" : "/subscriptions/6bd8b39f-86c3-4026-985a-34db67361301/resourceGroups/daf-lan1-d-euwe-rsg-aks/providers/Microsoft.ContainerRegistry/registries/acrakspzfu3h3wyefhu"}'
          command: 'build'
          Dockerfile: 'dotnet/AccountService_Dockerfile'

      - task: Docker@2
        inputs:
          containerRegistry: 'acrRegistryServiceConnection1'
          repository: '{"loginServer":"acrakspzfu3h3wyefhu.azurecr.io", "id" : "/subscriptions/6bd8b39f-86c3-4026-985a-34db67361301/resourceGroups/daf-lan1-d-euwe-rsg-aks/providers/Microsoft.ContainerRegistry/registries/acrakspzfu3h3wyefhu"}'
          command: 'push'
