# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

jobs:
  - job:
    variables:
      - group: DEV01-Build-Variables
      - name: subscription
        value: $(SUBSCRIPTION)
    pool: $(PRIVATEAGENT)
    steps:
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            cat dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            cat dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config
      - task: Docker@0
        displayName: 'Build an image'
        inputs:
          azureSubscription:  $(subscription)
          azureContainerRegistry: $(ContainerRegistry)
          dockerFile: dotnet/AccountService_Dockerfile
          imageName: accountservice-grpc-automatic
      - task: Docker@0
        displayName: 'Push an image'
        inputs:
          azureSubscription: $(subscription)
          azureContainerRegistry: $(ContainerRegistry)
          action: 'Push an image'
          imageName: accountservice-grpc-automatic

    
  - job:
    variables:
      - group: DEV0-Build-Variables
    pool: $(PRIVATEAGENT)
    steps:
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            cat dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json
      
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            cat dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config
      - task: Docker@0
        displayName: 'Build an image'
        inputs:
          azureSubscription:  'ats-sub1-d-app-automation'
          azureContainerRegistry: $(ContainerRegistry)
          dockerFile: dotnet/AccountService_Dockerfile
          imageName: accountservice-grpc-automatic
      - task: Docker@0
        displayName: 'Push an image'
        inputs:
          azureSubscription: 'ats-sub1-d-app-automation'
          azureContainerRegistry: $(ContainerRegistry)
          action: 'Push an image'
          imageName: accountservice-grpc-automatic
