 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

stages:
- stage: Build_for_Dev_1
  jobs:
  - deployment: 
    displayName: Build for Dev 1
    variables:
     - group: DEV01-Build-Variables
    pool:
     name: dafct-dev1-privateagent
    environment: 'smarthotel-dev'
    strategy:
    # default deployment strategy, more coming...
     runOnce:
      deploy:
       steps:
       - task: CmdLine@2
         inputs:
            script: |
              ls -a
              echo $(Subscription)
            