# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

jobs:
  - job:
    variables:
      - group: DEV0-Build-Variables
      - name: a
        value: $(Subscription)
    pool: $(PRIVATEAGENT)
    steps:
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            cat dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json
      
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
      - task: CmdLine@2
        inputs:
          script: |
            echo $(a)
      
