# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
- name: accountService
  displayName: Account Service
  type: boolean
  default: false
- name: reportService
  displayName: Report Service
  type: boolean
  default: false
  
pool: dafct-dta-privateagent

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo ${{ parameters.accountService}}
  condition: eq('{{ parameters.accountService }}', True)


