apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalservicerest-deployment
spec:
  selector:
    matchLabels:
      run: portalservicerest
  replicas: 2
  template:
    metadata:
      labels:
        run: portalservicerest
    spec:
      containers:
      - name: portalservicerest
        image: dafdev017756.azurecr.io/portalservicerest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: portalservice
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: portalservicerest
