apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalservice
spec:
  selector:
    matchLabels:
      run: portalservice
  replicas: 2
  template:
    metadata:
      labels:
        run: portalservice
    spec:
      containers:
      - name: portalservice
        image: dafdev017756.azurecr.io/portalservice-poc
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: portalservicepoc
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: portalservice
