parameters:
- name: subscription
  type: string
  default: 'subscription'
- name: containerRegistry
  type: string
  default: 'containerRegistry'
- name: variableGroup
  type: string
  default: 'variableGroup'

jobs:
  - job
    variables:
      - group: {{ parameters.variableGroup }}
    steps:
      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true

      - task: CmdLine@2
        inputs:
            script: |
              cat dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json

      - task: replacetokens@3
        inputs:
          targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true
          
      - task: CmdLine@2
        inputs:
          script: |
            echo $(Subscription)
            echo $(ContainerRegistry)
      
      - task: Docker@0
        displayName: 'Build an image'
        inputs:
          azureSubscription: ${{ parameters.Subscription }}
          azureContainerRegistry:  ${{ parameters.containerRegistry }}
          dockerFile: dotnet/AccountService_Dockerfile
          imageName: accountservice-grpc-automatic

      - task: Docker@0
        displayName: 'Push an image'
        inputs:
          azureSubscription:  ${{ parameters.Subscription }}
          azureContainerRegistry:  ${{ parameters.containerRegistry }}
          action: 'Push an image'
          imageName: accountservice-grpc-automatic