trigger:
- none

stages:
  - stage: stage1
    jobs:
    - template: simple-param.yaml  # Template reference
      parameters:
        subscription: 'ats-sub1-d-app-automation' # set to a non-boolean value to have the build fail
        containerRegistry: '{"loginServer":"dafdev017756.azurecr.io", "id" : "/subscriptions/f0b7c74e-ef18-46e8-ae31-7abbd0e5fd8f/resourceGroups/DAFCT_DEV0_DTA_K8S/providers/Microsoft.ContainerRegistry/registries/dafdev017756"}'
        variableGroup: 'DEV0-Build-Variables'
        privateAgent: 'ats-sub1-d-app-automation'
     

