trigger:
- none

jobs:
- job:
  pool: 'dafct-dta-privateagent'
  variables:
    group: DEV0-Build-Variables
  steps:
   - task: replacetokens@3
     inputs:
      targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      useLegacyPattern: false
      enableTelemetry: true

   - task: CmdLine@2
     inputs:
        script: |
          cat dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json

   - task: replacetokens@3
     inputs:
      targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      useLegacyPattern: false
      enableTelemetry: true
      
   - task: CmdLine@2
     inputs:
      script: |
        echo $(Subscription)
        echo $(ContainerRegistry)

   - template: simple-param.yaml  # Template reference
     parameters:
      subscription: 'ats-sub1-d-app-automation' # set to a non-boolean value to have the build fail
      containerRegistry: '{"loginServer":"dafdev017756.azurecr.io", "id" : "/subscriptions/f0b7c74e-ef18-46e8-ae31-7abbd0e5fd8f/resourceGroups/DAFCT_DEV0_DTA_K8S/providers/Microsoft.ContainerRegistry/registries/dafdev017756"}'
     

- job:
  pool: 'dafct-dev1-privateagent'
  variables:
    group: DEV01-Build-Variables
  steps:
   - task: replacetokens@3
     inputs:
      targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      useLegacyPattern: false
      enableTelemetry: true

   - task: CmdLine@2
     inputs:
      script: |
        cat dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.json

   - task: replacetokens@3
     inputs:
      targetFiles: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      useLegacyPattern: false
      enableTelemetry: true
      
   - task: CmdLine@2
     inputs:
      script: |
        echo $(Subscription)
        echo $(ContainerRegistry)

   - template: simple-param.yaml  # Template reference
     parameters:
      subscription: $(Subscription)
      containerRegistry: $(ContainerRegistry)
      
  