apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicleservice
spec:
  selector:
    matchLabels:
      run: vehicleservice
  replicas: 1
  template:
    metadata:
      labels:
        run: vehicleservice
    spec:
      containers:
      - name: vehicleservice
        image: dafdev017756.azurecr.io/vehicleservice
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: vehicleservice
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: vehicleservice
