
trigger:
- none

parameters:
- name: ENV
  displayName: ENV
  type: string
  default: DEV0
  values:
  - DEV0
  - DEV01
  - DEV02
  - TEST01
  - TEST02
  - ACC03
  - ACC01
  - ACC02
  - PRD01

pool: $(PRIVATEAGENT)

variables:
- ${{ if eq(parameters.ENV, 'DEV0') }}:
  - group: DEV0-Build-Variables
- ${{ if eq(parameters.ENV, 'DEV01') }}:
  - group: DEV01-Build-Variables
- ${{ if eq(parameters.ENV, 'DEV02') }}:
  - group: DEV02-Build-Variables
- ${{ if eq(parameters.ENV, 'TEST01') }}:
  - group: TEST01-Build-Variables
- ${{ if eq(parameters.ENV, 'TEST02') }}:
  - group: TEST02-Build-Variables
- ${{ if eq(parameters.ENV, 'ACC03') }}:
  - group: ACC03-Build-Variables
- ${{ if eq(parameters.ENV, 'ACC01') }}:
  - group: ACC01-Build-Variables
- ${{ if eq(parameters.ENV, 'ACC02') }}:
  - group: ACC02-Build-Variables
- ${{ if eq(parameters.ENV, 'PRD01') }}:
  - group: PRD01-Build-Variables

jobs:
- job: Build
  steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: 'poc/java/flinkcontainerization'
        artifact: manifestfiles
