apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticationdataservice
spec:
  selector:
    matchLabels:
      run: authenticationdataservice
  replicas: 2
  template:
    metadata:
      labels:
        run: authenticationdataservice
    spec:
      containers:
      - name: authenticationdataservice
        image: dafdev017756.azurecr.io/authenticationservicerest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: authenticationdataservice
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: authenticationdataservice
