
trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
  demands: maven

jobs:
- job: Build
  steps:
    - task: Maven@3
      displayName: 'Maven java/commoncomponent/daf.common/pom.xml'
      inputs:
        mavenPomFile: java/commoncomponent/daf.common/pom.xml
        publishJUnitResults: false

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
