apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerdataservice-deployment
  labels:
    app.kubernetes.io/name: customerdataservice
    app.kubernetes.io/type: dataservice
spec:
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app.kubernetes.io/name: customerdataservice
        app.kubernetes.io/type: dataservice
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10001
        runAsGroup: 3000
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - customerdataservice
              - key: app.kubernetes.io/type
                operator: In
                values:
                - dataservice
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: customerdataservice-container
        image: #{acrurl}#/customerdataservice
        imagePullPolicy: "Always"
        securityContext:
          allowPrivilegeEscalation: false
          #readOnlyRootFilesystem: true
          capabilities:
            drop:
             - all
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:8080"
        - name: COMPlus_EnableDiagnostics
          value: "0"
        ports:
          - containerPort: 8080
      nodeSelector:
        agentpool: npuser01         
  selector:
    matchLabels:
        app.kubernetes.io/name: customerdataservice
        app.kubernetes.io/type: dataservice
---
apiVersion: v1
kind: Service
metadata:
  name: customerdataservice
  labels:
    svc.kubernetes.io/name: customerdataservice
    svc.kubernetes.io/type: dataservice
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: customerdataservice
    app.kubernetes.io/type: dataservice

---
kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: customerdataservice-hpa
  labels:
    hpa.kubernetes.io/name: customerdataservice
    hpa.kubernetes.io/type: dataservice 
spec: 
  maxReplicas: 5 
  minReplicas: 2
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: customerdataservice-deployment 
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 70