apiVersion: apps/v1
kind: Deployment
metadata:
  name: singlesignonservice-deployment
spec:
  selector:
    matchLabels:
      run: singlesignonservice
  replicas: 2
  template:
    metadata:
      labels:
        run: singlesignonservice
    spec:
      containers:
      - name: singlesignonservice
        image: dafdev017756.azurecr.io/singlesignonservice
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: singlesignonservice
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: singlesignonservice