apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicledataservice
spec:
  selector:
    matchLabels:
      run: vehicledataservice
  replicas: 2
  template:
    metadata:
      labels:
        run: vehicledataservice
    spec:
      containers:
      - name: vehicledataservice
        image: dafdev017756.azurecr.io/vehicledataservice
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: vehicledataservice
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: vehicledataservice
