trigger:
- none

parameters:
- name: ENV
  displayName: ENV
  type: string
  default: DEV0
  values:
  - DEV0
  - DEV01
  - DEV02

variables:
- ${{ if eq(parameters.ENV, 'DEV0') }}:
  - group: DEV0-Release-Variables
- ${{ if eq(parameters.ENV, 'DEV01') }}:
  - group: DEV01-Release-Variables
- ${{ if eq(parameters.ENV, 'DEV02') }}:
  - group: DEV02-Release-Variables
  
jobs:
- job: Job_1
  displayName: Running Database Scripts
  pool:
    name: $(PRIVATEAGENT)
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
  - task: UseYuniqlCLI@1
    displayName: Use Yuniql
    
  - task: CmdLine@2
    inputs:
     script: 'export PGPASSWORD=$(PGDBPASSWORD2);psql -h dafct-dev0-dta-cdp-pgsql.postgres.database.azure.com -p 5432 -d Test -U pgadmin@dafct-dev0-dta-cdp-pgsql -c ''\set AUTOCOMMIT on'''
  
  - task: RunYuniqlCLI@1
    displayName: Run Yuniql
    inputs:
      connectionString: $(PGTESTDBCONNECTIONSTRING)
      workspacePath: $(PGMASTERDBSCRIPTS)
      targetPlatform: postgresql
      additionalArguments: --debug --environment $(ENVIRONMENT)
 
