create index if not exists  idx_subscription_subsidst ON master.subscription (subscription_id,state);
create index if not exists  idx_vehicle_orgid ON master.vehicle (organization_id);
create index if not exists  idx_group_grptyporgid on master.group(object_type,organization_id);
create index if not exists  idx_accessrelationship_vehgrpid on master.accessrelationship(vehicle_group_id);
create index if not exists  idx_accessrelationship_accgrpid on master.accessrelationship(account_group_id);
create index if not exists  idx_orgrelationshipmapping_enddate on master.orgrelationshipmapping(end_date);
create index if not exists  idx_orgrelationship_state on master.orgrelationship(state);
create index if not exists  idx_orgrelationship_code on master.orgrelationship(code);
create index if not exists  idx_orgrelationship_statecode on master.orgrelationship(code,state);
create index if not exists  idx_vehicle_modifiedat on master.vehicle(modified_at);
create index if not exists  idx_vehicle_vin ON master.vehicle (vin);
create index if not exists  idx_groupref_refid on master.groupref(ref_id);
create index if not exists  idx_vehicleaxcleproperties_vehicleid on master.vehiclefueltankproperties(vehicle_id);
create index if not exists  idx_group_grptyp_objtyp on master.group(group_type,object_type);
create index if not exists  idx_vehicle_status_orgid ON master.vehicle (status,organization_id);
create index if not exists  idx_group_objtyp on master.group(object_type);
create index if not exists  idx_vehicle_id_regpltno ON master.vehicle (id,license_plate_number);
create index if not exists  idx_vehicle_regpltno ON master.vehicle (license_plate_number);
create index if not exists  idx_vehicle_idname ON master.vehicle (id,name);
create index if not exists  idx_accountpreference_stateid ON master.accountpreference (state,id);
create index if not exists  idx_accountorg_orgidstate ON master.accountorg (organization_id,state);
create index if not exists  idx_accountorg_state ON master.accountorg (state);
create index if not exists  idx_account_state ON master.account (state);
create index if not exists  idx_account_email ON master.account (lower(email));
create index if not exists  idx_accessrelationship_accgrpidvehgrpidacctyp on master.accessrelationship(access_type,account_group_id,vehicle_group_id);
create index if not exists  idx_group_orgid on master.group(organization_id);
create index if not exists  idx_vehicle_orgidname on master.vehicle(organization_id,length(name));
create index if not exists  idx_resetpasswordtoken_accidstatus on master.ResetPasswordToken(account_id,status);								
create index if not exists  idx_translation_code on translation.translation(code);								
create index if not exists  idx_subscription_orgidstate on master.subscription(organization_id,state);								
create index if not exists  idx_account_pref on master.account(preference_id);
create index if not exists  idx_passwordpolicy_isblkisremstmodat on master.passwordpolicy(is_blocked ,is_reminder_sent ,modified_at);
create index if not exists  idx_vehicleaxleproperties_vehid on master.vehicleaxleproperties(vehicle_id);
create index if not exists  idx_vehiclefueltankproperties_vehid on master.vehiclefueltankproperties(vehicle_id);
create index if not exists idx_vehicle_idregpltno on master.vehicle(id,license_plate_number)  ;
create index if not exists idx_vehicle_idnm on master.vehicle(id,name)  ;
create index if not exists  idx_resetpasswordtoken_tknststatus on master.ResetPasswordToken(token_secret,status);								

create index if not exists idx_alerturgencylevelref on master.alerturgencylevelref (alert_id,urgency_level_type,state);  								 
create index if not exists idx_ecoscoreprofilekpi_espid on master.ecoscoreprofilekpi (ecoscore_profile_id);								 
create index if not exists idx_reportpreference_orgidaccidrepid on master.reportpreference (organization_id,account_id,report_id);											
create index if not exists idx_reportattribure_repid on master.reportattribute (report_id);											
