apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: customerdataservice-ingress
spec:
  rules:
  - host: #{IngressURL}#
    http:
      paths:
      - backend:
          serviceName: customerdataservice
          servicePort: 80
        path: /swagger
      - backend:
          serviceName: customerdataservice
          servicePort: 80
        path: /customer-data
      - backend:
          serviceName: authenticationservice
          servicePort: 80
        path: /Auth
      - backend:
          serviceName: accountservice
          servicePort: 80
        path: /Account
      - backend:
          serviceName: uimanagement-service
          servicePort: 80
        path: /  
  tls:
  - hosts:
    - #{IngressURL}#