// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: audittrail.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace net.atos.daf.ct2.auditclient {

  /// <summary>Holder for reflection information generated from audittrail.proto</summary>
  public static partial class AudittrailReflection {

    #region Descriptor
    /// <summary>File descriptor for audittrail.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AudittrailReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBhdWRpdHRyYWlsLnByb3RvEgphdWRpdHRyYWlsGh9nb29nbGUvcHJvdG9i",
            "dWYvdGltZXN0YW1wLnByb3RvIuMDCgtBdWRpdFJlY29yZBIUCgxBdWRpdHRy",
            "YWlsaWQYASABKAUSMAoMUGVyZm9ybWVkX2F0GAIgASgLMhouZ29vZ2xlLnBy",
            "b3RvYnVmLlRpbWVzdGFtcBIUCgxQZXJmb3JtZWRfYnkYAyABKAUSFgoOQ29t",
            "cG9uZW50X25hbWUYBCABKAkSFAoMU2VydmljZV9uYW1lGAUgASgJEjAKBFR5",
            "cGUYBiABKA4yIi5hdWRpdHRyYWlsLkF1ZGl0UmVjb3JkLkV2ZW50X3R5cGUS",
            "NAoGU3RhdHVzGAcgASgOMiQuYXVkaXR0cmFpbC5BdWRpdFJlY29yZC5FdmVu",
            "dF9zdGF0dXMSDwoHTWVzc2FnZRgIIAEoCRIXCg9Tb3VyY2VvYmplY3RfaWQY",
            "CSABKAUSFwoPVGFyZ2V0b2JqZWN0X2lkGAogASgFEhQKDFVwZGF0ZWRfZGF0",
            "YRgLIAEoCSJECgpFdmVudF90eXBlEgkKBUxPR0lOEAASCgoGQ1JFQVRFEAES",
            "CgoGVVBEQVRFEAISCgoGREVMRVRFEAMSBwoDR0VUEAQiQQoMRXZlbnRfc3Rh",
            "dHVzEgsKB1NVQ0NFU1MQABIKCgZGQUlMRUQQARILCgdQRU5ESU5HEAISCwoH",
            "QUJPUlRFRBADIjQKDUF1ZGl0UmVzcG9uY2USEgoKc3RhdHVzY29kZRgBIAEo",
            "CRIPCgdtZXNzYWdlGAIgASgJIpQBCgxBdWRpdFJlcXVlc3QSFQoNY29tcG9u",
            "ZW50bmFtZRgBIAEoCRIRCglldmVudHR5cGUYAiABKAkSLQoJc3RhcnR0aW1l",
            "GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIrCgdlbmR0aW1l",
            "GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcDJNCgxBdWRpdFNl",
            "cnZpY2USPQoHQWRkbG9ncxIXLmF1ZGl0dHJhaWwuQXVkaXRSZWNvcmQaGS5h",
            "dWRpdHRyYWlsLkF1ZGl0UmVzcG9uY2VCH6oCHG5ldC5hdG9zLmRhZi5jdDIu",
            "YXVkaXRjbGllbnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::net.atos.daf.ct2.auditclient.AuditRecord), global::net.atos.daf.ct2.auditclient.AuditRecord.Parser, new[]{ "Audittrailid", "PerformedAt", "PerformedBy", "ComponentName", "ServiceName", "Type", "Status", "Message", "SourceobjectId", "TargetobjectId", "UpdatedData" }, null, new[]{ typeof(global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type), typeof(global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::net.atos.daf.ct2.auditclient.AuditResponce), global::net.atos.daf.ct2.auditclient.AuditResponce.Parser, new[]{ "Statuscode", "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::net.atos.daf.ct2.auditclient.AuditRequest), global::net.atos.daf.ct2.auditclient.AuditRequest.Parser, new[]{ "Componentname", "Eventtype", "Starttime", "Endtime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AuditRecord : pb::IMessage<AuditRecord>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuditRecord> _parser = new pb::MessageParser<AuditRecord>(() => new AuditRecord());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AuditRecord> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::net.atos.daf.ct2.auditclient.AudittrailReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditRecord() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditRecord(AuditRecord other) : this() {
      audittrailid_ = other.audittrailid_;
      performedAt_ = other.performedAt_ != null ? other.performedAt_.Clone() : null;
      performedBy_ = other.performedBy_;
      componentName_ = other.componentName_;
      serviceName_ = other.serviceName_;
      type_ = other.type_;
      status_ = other.status_;
      message_ = other.message_;
      sourceobjectId_ = other.sourceobjectId_;
      targetobjectId_ = other.targetobjectId_;
      updatedData_ = other.updatedData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditRecord Clone() {
      return new AuditRecord(this);
    }

    /// <summary>Field number for the "Audittrailid" field.</summary>
    public const int AudittrailidFieldNumber = 1;
    private int audittrailid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Audittrailid {
      get { return audittrailid_; }
      set {
        audittrailid_ = value;
      }
    }

    /// <summary>Field number for the "Performed_at" field.</summary>
    public const int PerformedAtFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp performedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp PerformedAt {
      get { return performedAt_; }
      set {
        performedAt_ = value;
      }
    }

    /// <summary>Field number for the "Performed_by" field.</summary>
    public const int PerformedByFieldNumber = 3;
    private int performedBy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PerformedBy {
      get { return performedBy_; }
      set {
        performedBy_ = value;
      }
    }

    /// <summary>Field number for the "Component_name" field.</summary>
    public const int ComponentNameFieldNumber = 4;
    private string componentName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ComponentName {
      get { return componentName_; }
      set {
        componentName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Service_name" field.</summary>
    public const int ServiceNameFieldNumber = 5;
    private string serviceName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServiceName {
      get { return serviceName_; }
      set {
        serviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 6;
    private global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type type_ = global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Status" field.</summary>
    public const int StatusFieldNumber = 7;
    private global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status status_ = global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 8;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Sourceobject_id" field.</summary>
    public const int SourceobjectIdFieldNumber = 9;
    private int sourceobjectId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SourceobjectId {
      get { return sourceobjectId_; }
      set {
        sourceobjectId_ = value;
      }
    }

    /// <summary>Field number for the "Targetobject_id" field.</summary>
    public const int TargetobjectIdFieldNumber = 10;
    private int targetobjectId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TargetobjectId {
      get { return targetobjectId_; }
      set {
        targetobjectId_ = value;
      }
    }

    /// <summary>Field number for the "Updated_data" field.</summary>
    public const int UpdatedDataFieldNumber = 11;
    private string updatedData_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UpdatedData {
      get { return updatedData_; }
      set {
        updatedData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AuditRecord);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AuditRecord other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Audittrailid != other.Audittrailid) return false;
      if (!object.Equals(PerformedAt, other.PerformedAt)) return false;
      if (PerformedBy != other.PerformedBy) return false;
      if (ComponentName != other.ComponentName) return false;
      if (ServiceName != other.ServiceName) return false;
      if (Type != other.Type) return false;
      if (Status != other.Status) return false;
      if (Message != other.Message) return false;
      if (SourceobjectId != other.SourceobjectId) return false;
      if (TargetobjectId != other.TargetobjectId) return false;
      if (UpdatedData != other.UpdatedData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Audittrailid != 0) hash ^= Audittrailid.GetHashCode();
      if (performedAt_ != null) hash ^= PerformedAt.GetHashCode();
      if (PerformedBy != 0) hash ^= PerformedBy.GetHashCode();
      if (ComponentName.Length != 0) hash ^= ComponentName.GetHashCode();
      if (ServiceName.Length != 0) hash ^= ServiceName.GetHashCode();
      if (Type != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type.Login) hash ^= Type.GetHashCode();
      if (Status != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status.Success) hash ^= Status.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (SourceobjectId != 0) hash ^= SourceobjectId.GetHashCode();
      if (TargetobjectId != 0) hash ^= TargetobjectId.GetHashCode();
      if (UpdatedData.Length != 0) hash ^= UpdatedData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Audittrailid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Audittrailid);
      }
      if (performedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PerformedAt);
      }
      if (PerformedBy != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PerformedBy);
      }
      if (ComponentName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ComponentName);
      }
      if (ServiceName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ServiceName);
      }
      if (Type != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type.Login) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Type);
      }
      if (Status != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status.Success) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Status);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Message);
      }
      if (SourceobjectId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(SourceobjectId);
      }
      if (TargetobjectId != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(TargetobjectId);
      }
      if (UpdatedData.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(UpdatedData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Audittrailid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Audittrailid);
      }
      if (performedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PerformedAt);
      }
      if (PerformedBy != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PerformedBy);
      }
      if (ComponentName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ComponentName);
      }
      if (ServiceName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ServiceName);
      }
      if (Type != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type.Login) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Type);
      }
      if (Status != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status.Success) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Status);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Message);
      }
      if (SourceobjectId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(SourceobjectId);
      }
      if (TargetobjectId != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(TargetobjectId);
      }
      if (UpdatedData.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(UpdatedData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Audittrailid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Audittrailid);
      }
      if (performedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PerformedAt);
      }
      if (PerformedBy != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PerformedBy);
      }
      if (ComponentName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ComponentName);
      }
      if (ServiceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceName);
      }
      if (Type != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Status != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (SourceobjectId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceobjectId);
      }
      if (TargetobjectId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetobjectId);
      }
      if (UpdatedData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UpdatedData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AuditRecord other) {
      if (other == null) {
        return;
      }
      if (other.Audittrailid != 0) {
        Audittrailid = other.Audittrailid;
      }
      if (other.performedAt_ != null) {
        if (performedAt_ == null) {
          PerformedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        PerformedAt.MergeFrom(other.PerformedAt);
      }
      if (other.PerformedBy != 0) {
        PerformedBy = other.PerformedBy;
      }
      if (other.ComponentName.Length != 0) {
        ComponentName = other.ComponentName;
      }
      if (other.ServiceName.Length != 0) {
        ServiceName = other.ServiceName;
      }
      if (other.Type != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type.Login) {
        Type = other.Type;
      }
      if (other.Status != global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status.Success) {
        Status = other.Status;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.SourceobjectId != 0) {
        SourceobjectId = other.SourceobjectId;
      }
      if (other.TargetobjectId != 0) {
        TargetobjectId = other.TargetobjectId;
      }
      if (other.UpdatedData.Length != 0) {
        UpdatedData = other.UpdatedData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Audittrailid = input.ReadInt32();
            break;
          }
          case 18: {
            if (performedAt_ == null) {
              PerformedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PerformedAt);
            break;
          }
          case 24: {
            PerformedBy = input.ReadInt32();
            break;
          }
          case 34: {
            ComponentName = input.ReadString();
            break;
          }
          case 42: {
            ServiceName = input.ReadString();
            break;
          }
          case 48: {
            Type = (global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type) input.ReadEnum();
            break;
          }
          case 56: {
            Status = (global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status) input.ReadEnum();
            break;
          }
          case 66: {
            Message = input.ReadString();
            break;
          }
          case 72: {
            SourceobjectId = input.ReadInt32();
            break;
          }
          case 80: {
            TargetobjectId = input.ReadInt32();
            break;
          }
          case 90: {
            UpdatedData = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Audittrailid = input.ReadInt32();
            break;
          }
          case 18: {
            if (performedAt_ == null) {
              PerformedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PerformedAt);
            break;
          }
          case 24: {
            PerformedBy = input.ReadInt32();
            break;
          }
          case 34: {
            ComponentName = input.ReadString();
            break;
          }
          case 42: {
            ServiceName = input.ReadString();
            break;
          }
          case 48: {
            Type = (global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_type) input.ReadEnum();
            break;
          }
          case 56: {
            Status = (global::net.atos.daf.ct2.auditclient.AuditRecord.Types.Event_status) input.ReadEnum();
            break;
          }
          case 66: {
            Message = input.ReadString();
            break;
          }
          case 72: {
            SourceobjectId = input.ReadInt32();
            break;
          }
          case 80: {
            TargetobjectId = input.ReadInt32();
            break;
          }
          case 90: {
            UpdatedData = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AuditRecord message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Event_type {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("CREATE")] Create = 1,
        [pbr::OriginalName("UPDATE")] Update = 2,
        [pbr::OriginalName("DELETE")] Delete = 3,
        [pbr::OriginalName("GET")] Get = 4,
      }

      public enum Event_status {
        [pbr::OriginalName("SUCCESS")] Success = 0,
        [pbr::OriginalName("FAILED")] Failed = 1,
        [pbr::OriginalName("PENDING")] Pending = 2,
        [pbr::OriginalName("ABORTED")] Aborted = 3,
      }

    }
    #endregion

  }

  public sealed partial class AuditResponce : pb::IMessage<AuditResponce>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuditResponce> _parser = new pb::MessageParser<AuditResponce>(() => new AuditResponce());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AuditResponce> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::net.atos.daf.ct2.auditclient.AudittrailReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditResponce() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditResponce(AuditResponce other) : this() {
      statuscode_ = other.statuscode_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditResponce Clone() {
      return new AuditResponce(this);
    }

    /// <summary>Field number for the "statuscode" field.</summary>
    public const int StatuscodeFieldNumber = 1;
    private string statuscode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Statuscode {
      get { return statuscode_; }
      set {
        statuscode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AuditResponce);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AuditResponce other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Statuscode != other.Statuscode) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Statuscode.Length != 0) hash ^= Statuscode.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Statuscode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Statuscode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Statuscode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Statuscode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Statuscode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Statuscode);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AuditResponce other) {
      if (other == null) {
        return;
      }
      if (other.Statuscode.Length != 0) {
        Statuscode = other.Statuscode;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Statuscode = input.ReadString();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Statuscode = input.ReadString();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AuditRequest : pb::IMessage<AuditRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuditRequest> _parser = new pb::MessageParser<AuditRequest>(() => new AuditRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AuditRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::net.atos.daf.ct2.auditclient.AudittrailReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditRequest(AuditRequest other) : this() {
      componentname_ = other.componentname_;
      eventtype_ = other.eventtype_;
      starttime_ = other.starttime_ != null ? other.starttime_.Clone() : null;
      endtime_ = other.endtime_ != null ? other.endtime_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditRequest Clone() {
      return new AuditRequest(this);
    }

    /// <summary>Field number for the "componentname" field.</summary>
    public const int ComponentnameFieldNumber = 1;
    private string componentname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Componentname {
      get { return componentname_; }
      set {
        componentname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "eventtype" field.</summary>
    public const int EventtypeFieldNumber = 2;
    private string eventtype_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Eventtype {
      get { return eventtype_; }
      set {
        eventtype_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "starttime" field.</summary>
    public const int StarttimeFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp starttime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Starttime {
      get { return starttime_; }
      set {
        starttime_ = value;
      }
    }

    /// <summary>Field number for the "endtime" field.</summary>
    public const int EndtimeFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp endtime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Endtime {
      get { return endtime_; }
      set {
        endtime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AuditRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AuditRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Componentname != other.Componentname) return false;
      if (Eventtype != other.Eventtype) return false;
      if (!object.Equals(Starttime, other.Starttime)) return false;
      if (!object.Equals(Endtime, other.Endtime)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Componentname.Length != 0) hash ^= Componentname.GetHashCode();
      if (Eventtype.Length != 0) hash ^= Eventtype.GetHashCode();
      if (starttime_ != null) hash ^= Starttime.GetHashCode();
      if (endtime_ != null) hash ^= Endtime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Componentname.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Componentname);
      }
      if (Eventtype.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Eventtype);
      }
      if (starttime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Starttime);
      }
      if (endtime_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Endtime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Componentname.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Componentname);
      }
      if (Eventtype.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Eventtype);
      }
      if (starttime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Starttime);
      }
      if (endtime_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Endtime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Componentname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Componentname);
      }
      if (Eventtype.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Eventtype);
      }
      if (starttime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Starttime);
      }
      if (endtime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Endtime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AuditRequest other) {
      if (other == null) {
        return;
      }
      if (other.Componentname.Length != 0) {
        Componentname = other.Componentname;
      }
      if (other.Eventtype.Length != 0) {
        Eventtype = other.Eventtype;
      }
      if (other.starttime_ != null) {
        if (starttime_ == null) {
          Starttime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Starttime.MergeFrom(other.Starttime);
      }
      if (other.endtime_ != null) {
        if (endtime_ == null) {
          Endtime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Endtime.MergeFrom(other.Endtime);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Componentname = input.ReadString();
            break;
          }
          case 18: {
            Eventtype = input.ReadString();
            break;
          }
          case 26: {
            if (starttime_ == null) {
              Starttime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Starttime);
            break;
          }
          case 34: {
            if (endtime_ == null) {
              Endtime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Endtime);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Componentname = input.ReadString();
            break;
          }
          case 18: {
            Eventtype = input.ReadString();
            break;
          }
          case 26: {
            if (starttime_ == null) {
              Starttime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Starttime);
            break;
          }
          case 34: {
            if (endtime_ == null) {
              Endtime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Endtime);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
