// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: audittrail.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace net.atos.daf.ct2.auditclient {
  public static partial class AuditService
  {
    static readonly string __ServiceName = "audittrail.AuditService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::net.atos.daf.ct2.auditclient.AuditRecord> __Marshaller_audittrail_AuditRecord = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::net.atos.daf.ct2.auditclient.AuditRecord.Parser));
    static readonly grpc::Marshaller<global::net.atos.daf.ct2.auditclient.AuditResponce> __Marshaller_audittrail_AuditResponce = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::net.atos.daf.ct2.auditclient.AuditResponce.Parser));

    static readonly grpc::Method<global::net.atos.daf.ct2.auditclient.AuditRecord, global::net.atos.daf.ct2.auditclient.AuditResponce> __Method_Addlogs = new grpc::Method<global::net.atos.daf.ct2.auditclient.AuditRecord, global::net.atos.daf.ct2.auditclient.AuditResponce>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Addlogs",
        __Marshaller_audittrail_AuditRecord,
        __Marshaller_audittrail_AuditResponce);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::net.atos.daf.ct2.auditclient.AudittrailReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AuditService</summary>
    [grpc::BindServiceMethod(typeof(AuditService), "BindService")]
    public abstract partial class AuditServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::net.atos.daf.ct2.auditclient.AuditResponce> Addlogs(global::net.atos.daf.ct2.auditclient.AuditRecord request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AuditService</summary>
    public partial class AuditServiceClient : grpc::ClientBase<AuditServiceClient>
    {
      /// <summary>Creates a new client for AuditService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AuditServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AuditService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AuditServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AuditServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AuditServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::net.atos.daf.ct2.auditclient.AuditResponce Addlogs(global::net.atos.daf.ct2.auditclient.AuditRecord request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Addlogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::net.atos.daf.ct2.auditclient.AuditResponce Addlogs(global::net.atos.daf.ct2.auditclient.AuditRecord request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Addlogs, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::net.atos.daf.ct2.auditclient.AuditResponce> AddlogsAsync(global::net.atos.daf.ct2.auditclient.AuditRecord request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddlogsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::net.atos.daf.ct2.auditclient.AuditResponce> AddlogsAsync(global::net.atos.daf.ct2.auditclient.AuditRecord request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Addlogs, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AuditServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AuditServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AuditServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Addlogs, serviceImpl.Addlogs).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AuditServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Addlogs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::net.atos.daf.ct2.auditclient.AuditRecord, global::net.atos.daf.ct2.auditclient.AuditResponce>(serviceImpl.Addlogs));
    }

  }
}
#endregion
