trigger:
- none

parameters:
- name: ENV
  displayName: ENV
  type: string
  default: DEV0
  values:
  - DEV0
  - DEV01
  - DEV02
  - TEST01
  - TEST02
  - ACC03
  - ACC01
  - ACC02

variables:
- ${{ if eq(parameters.ENV, 'DEV0') }}:
  - group: DEV0-Build-Variables
- ${{ if eq(parameters.ENV, 'DEV01') }}:
  - group: DEV01-Build-Variables
- ${{ if eq(parameters.ENV, 'DEV02') }}:
  - group: DEV02-Build-Variables
- ${{ if eq(parameters.ENV, 'TEST01') }}:
  - group: TEST01-Build-Variables
- ${{ if eq(parameters.ENV, 'TEST02') }}:
  - group: TEST02-Build-Variables
- ${{ if eq(parameters.ENV, 'ACC03') }}:
  - group: ACC03-Build-Variables
- ${{ if eq(parameters.ENV, 'ACC01') }}:
  - group: ACC01-Build-Variables
- ${{ if eq(parameters.ENV, 'ACC02') }}:
  - group: ACC02-Build-Variables
  
pool: $(PRIVATEAGENT)

steps:
- task: replacetokens@3
  inputs:
    targetFiles: 'ui/src/assets/config/default.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true

- task: CmdLine@2
  inputs:
    script: |
      cat ui/src/assets/config/default.json
      export NODE_OPTIONS=--max-old-space-size=8192

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription:  $(Subscription)
    azureContainerRegistry: $(ContainerRegistry)
    dockerFile: ui/dockerfilefront
    imageName: uiservice

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: $(Subscription)
    azureContainerRegistry: $(ContainerRegistry)
    action: 'Push an image'
    imageName: uiservice
