apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticationdataservice-auto-deployment
spec:
  selector:
    matchLabels:
      run: authenticationdataservice-auto
  replicas: 2
  template:
    metadata:
      labels:
        run: authenticationdataservice-auto
    spec:
      containers:
      - name: authenticationservicerest-auto
        image: dafdev017756.azurecr.io/authenticationservicerest-auto
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: authenticationdataservice-auto
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: authenticationdataservice-auto
