apiVersion: apps/v1
kind: Deployment
metadata:
  name: driverservice-grpc
spec:
  selector:
    matchLabels:
      run: driverservice-grpc
  replicas: 2
  template:
    metadata:
      labels:
        run: driverservice-grpc
    spec:
      containers:
      - name: driverservice-grpc
        image: dafdev017756.azurecr.io/driverservice
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: driverservice
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: driverservice-grpc
