apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcuprovisioningvehicleservice
spec:
  selector:
    matchLabels:
      run: tcuprovisioningvehicleservice
  replicas: 2
  template:
    metadata:
      labels:
        run: tcuprovisioningvehicleservice
    spec:
      containers:
      - name: tcuprovisioningvehicleservice
        image: dafdev017756.azurecr.io/tcuprovisioningvehicleservice
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: tcuprovisioningvehicleservice
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: tcuprovisioningvehicleservice
