trigger:
- none
#  branches:
#    include:
#    - development
#    - release
#    - testing
#    - master 
#  paths:
#    include:
#    - dotnet/businessservices/net.atos.daf.ct2.accountservice

variables:
 - name: imagerepository
   value: 'testservice-auto'
 - name: dockerFile
   value: 'dotnet/test_Dockerfile'
 - name: manifestFile
   value: 'devops/self\ triggered\ pipelines/testserviceauto-grpc-dotnet-kubernetes-manifest-dev1-dev2.yaml'
 - name: manifestFileDev0
   value: 'devops/self\ triggered\ pipelines/testserviceauto-grpc-dotnet-kubernetes-manifest.yaml'
 - name: appsettingsFile
   value: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/appsettings.Production.json'
 - name: log4netConfigFile
   value: 'dotnet/businessservices/net.atos.daf.ct2.accountservice/log4net.config'


stages:
  - stage: stage_dev2
    jobs:
    - template: dotnet-pipeline-template.yaml  # Template reference
      parameters:
        containerRegistry: 'acraksoxvoiq64cpv6y'
        variableGroup: 'DEV02-Build-Variables'
        dockerFile: $(dockerFile)
        manifestFile: $(manifestFile)
        appsettingsPath: $(appsettingsFile)
        log4netConfigPath: $(log4netConfigFile)
        imagerepository: $(imagerepository)
    condition: eq(variables['Build.SourceBranchName'],  'development')

  - stage: stage_tst1
    jobs:
    - template: dotnet-pipeline-template.yaml  # Template reference
      parameters:
        containerRegistry: 'acraksoxvoiq64cpv6y'
        variableGroup: 'TEST01-Build-Variables'
        dockerFile: $(dockerFile)
        manifestFile: $(manifestFile)
        appsettingsPath: $(appsettingsFile)
        log4netConfigPath: $(log4netConfigFile)
        imagerepository: $(imagerepository)
    condition: eq(variables['Build.SourceBranchName'],  'testing')