create index if not exists  idx_livefleetpositionstatistics_vintrpid 	ON livefleet.livefleet_position_statistics (vin,trip_id);
create index if not exists  idx_tripalert_vin ON tripdetail.tripalert (vin );
create index if not exists  idx_livefleetcurrenttripstatistics_drvid ON livefleet.livefleet_current_trip_statistics (driver1_id );
create index if not exists  idx_driver_drvid ON master.driver (driver_id);
create index if not exists  idx_tripdetailtripstatistics_sttsedtsvin ON tripdetail.trip_statistics (start_time_stamp,end_time_stamp,vin);
create index if not exists  idx_tripdetailtripstatistics_isogtrpendtsvin ON tripdetail.trip_statistics ((not is_ongoing_trip),end_time_stamp,vin);
create index if not exists  idx_tripdetailtripstatistics_vin ON tripdetail.trip_statistics (vin);
create index if not exists  idx_livefleetpositionstatistics_vehmsgtyp 	ON livefleet.livefleet_position_statistics (veh_message_type);
create index if not exists  idx_tripalert_tripid ON tripdetail.tripalert (trip_id );
create index if not exists  idx_livefleetpositionstatistics_msgtdtrgtypmsgtyp 	ON livefleet.livefleet_position_statistics (message_time_stamp,vehicle_msg_trigger_type_id, veh_message_type);
create index if not exists  idx_livefleetcurrenttripstatistics_tripid ON livefleet.livefleet_current_trip_statistics (trip_id );
create index if not exists  idx_livefleetcurrenttripstatistics_vin ON livefleet.livefleet_current_trip_statistics (vin);
create index if not exists  idx_tripalert_alertcat ON tripdetail.tripalert (category_type);
create index if not exists  idx_tripalert_alertcaturglvl ON tripdetail.tripalert (category_type,urgency_level_type);
create index if not exists  idx_livefleetcurrenttripstatistics_latlong ON livefleet.livefleet_current_trip_statistics (TRUNC(CAST(latest_received_position_lattitude as numeric),4),TRUNC(CAST(latest_received_position_longitude as numeric),4));
create index if not exists  idx_tripalert_latlong ON tripdetail.tripalert (TRUNC(CAST(latitude as numeric),4),TRUNC(CAST(longitude as numeric),4));
create index if not exists  idx_geolocationaddress_latlong ON master.geolocationaddress (TRUNC(CAST(latitude as numeric),4),TRUNC(CAST(longitude as numeric),4));
create index if not exists  idx_tripalert_alerturglvl ON tripdetail.tripalert (urgency_level_type);
create index if not exists  idx_livefleetcurrenttripstatistics_drvidhltstttyp ON livefleet.livefleet_current_trip_statistics (driver1_id,vehicle_health_status_type);
create index if not exists  idx_livefleetpositionstatistics_vin ON livefleet.livefleet_position_statistics (vin);
create index if not exists  idx_driver_orgid ON master.driver (organization_id);
create index if not exists  idx_tripstatistics_drvid ON tripdetail.trip_statistics (driver1_id );
create index if not exists  idx_vehicle_mdat on  master.vehicle (modified_at);										
create index if not exists  idx_vehiclemileage_mdat on  mileage.vehiclemileage (modified_at);																				
create index if not exists  idx_livefleetcurrenttripstatistics_drvidsttsendts ON livefleet.livefleet_current_trip_statistics (driver1_id,start_time_stamp,end_time_stamp);

create index if not exists  idx_fueldeviation_trpid on livefleet.livefleet_trip_fuel_deviation (trip_id);
create index if not exists  idx_tripdriveractivity_actdtdrvidvin on livefleet.livefleet_trip_driver_activity (activity_date,driver_id,vin);
create index if not exists  idx_tripdriveractivity_strttendtdrvid on livefleet.livefleet_trip_driver_activity (start_time,end_time,driver_id);
create index if not exists  idx_ecoscoredata_sttsedtsvin on tripdetail.ecoscoredata (start_time,end_time,vin);								 
create index if not exists  idx_ecoscoredata_sttsedtsvintrpdisdrv on tripdetail.ecoscoredata (start_time,end_time,vin,trip_distance,driver1_id);
